//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teammy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignee
    {
        public long assignee_id { get; set; }
        public Nullable<int> assigned_group { get; set; }
        public Nullable<long> mate_id { get; set; }
    
        public virtual team_mates team_mates { get; set; }
    }
}
