//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teammy
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public long task_id { get; set; }
        public string task_name { get; set; }
        public Nullable<long> proj_id { get; set; }
        public Nullable<int> assigned_group { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string progress_code { get; set; }
        public Nullable<long> category_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual progress_indicators progress_indicators { get; set; }
        public virtual project project { get; set; }
    }
}
